# Generated by Django 4.2.4 on 2023-08-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_aprendiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='document_num',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='document_type',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='ficha_num',
            field=models.IntegerField(max_length=8),
        ),
    ]
