# Generated by Django 4.2.4 on 2023-08-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_aprendiz', '0002_alter_aprendiz_document_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='document_num',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='ficha_num',
            field=models.CharField(max_length=8),
        ),
    ]
